In [1]:
import pandas as pd
file_path = './data/chipotle.tsv'
chipo = pd.read_csv(file_path,sep='\t')
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [2]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [3]:
chipo['item_price'].head()

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
Name: item_price, dtype: object

In [4]:
x = '$4.99'
type(x)

str

In [5]:
x[1:]

'4.99'

In [6]:
float(x[1:])

4.99

In [7]:
# column 단위 데이터에 apply()함수로 전처리를 적용한다.
chipo['item_price'].apply(lambda x : float(x[1:]))
chipo.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [8]:
# processin
chipo['order_id'] = chipo['order_id'].astype('str')
chipo['item_price'] = chipo['item_price'].apply(lambda x : float (x[1:]))
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [9]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   object
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 180.7+ KB

In [10]:
chipo.groupby('order_id')['item_price'].sum()

order_id
1       11.56
10      13.20
100     10.08
1000    20.50
1001    10.08
        ...
995     24.95
996     43.00
997     22.50
998     10.88
999     29.25
Name: item_price, Length: 1834, dtype: float64

In [11]:
# 주문당 평균 계산금액을 출력한다.
chipo.groupby('order_id')['item_price'].sum().mean()

18.811428571428717

In [12]:
# 한 주문에 30달러 이상 지불한 주문 번호('order_id') 출력하기
chipo_orderid_group = chipo.groupby('order_id').sum()
results = chipo_orderid_group[chipo_orderid_group.item_price >= 30]
print(results[:10])
print(results.index.values)

          quantity  item_price
order_id
1006             8       71.40
1010             5       33.24
1013             4       31.90
1016             3       32.25
1026             4       31.70
103              6       47.90
1035             4       32.04
1051             7       59.35
1052             4       38.20
1057             3       31.25
['1006' '1010' '1013' '1016' '1026' '103' '1035' '1051' '1052' '1057'
 '1070' '1071' '1082' '1091' '110' '1167' '1170' '1176' '1182' '1189'
 '1193' '1223' '1228' '1243' '1248' '125' '1271' '1323' '1341' '1356'
 '1360' '1367' '1398' '1402' '1426' '1431' '1443' '1449' '1453' '1454'
 '1461' '148' '1483' '149' '1511' '1533' '1554' '1559' '1577' '1586'
 '1592' '1598' '1601' '1615' '1648' '1655' '1660' '1679' '1699' '1703'
 '1718' '1719' '1737' '1738' '1761' '1764' '1766' '1768' '1772' '178'
 '1786' '1825' '1827' '184' '186' '195' '20' '205' '230' '231' '234' '235'
 '247' '276' '28' '284' '304' '311' '326' '343' '346' '379' '384' '387'
 '389' '40' '400' '402' '481' '488' '491' '511' '529' '534' '552' '561'
 '576' '577' '623' '628' '635' '649' '654' '688' '691' '708' '734' '737'
 '75' '759' '787' '791' '806' '814' '816' '818' '823' '848' '879' '881'
 '888' '901' '907' '913' '916' '926' '93' '948' '949' '953' '96' '973'
 '996']

In [13]:
# 각 아이템의 가격 구하기
chipo_one_item = chipo[chipo.quantity == 1]
chipo_one_item.groupby('item_name').min()

,order_id,quantity,choice_description,item_price
item_name,,,,
6 Pack Soft Drink,1076,1,[Coke],6.49
Barbacoa Bowl,1000,1,"[Fresh Tomato (Mild), [Lettuce, Black Beans, R...",8.69
Barbacoa Burrito,1002,1,"[Fresh Tomato (Mild), [Black Beans, Rice, Sour...",8.69
Barbacoa Crispy Tacos,110,1,"[Fresh Tomato Salsa, Guacamole]",8.99
Barbacoa Salad Bowl,1283,1,"[Fresh Tomato Salsa, Guacamole]",9.39
Barbacoa Soft Tacos,1103,1,"[Fresh Tomato Salsa, [Black Beans, Cheese, Let...",8.99
Bottled Water,1009,1,NaN,1.09
Bowl,279,1,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",7.40
Burrito,214,1,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",7.40
Canned Soda,100,1,[Coca Cola],1.09
Canned Soft Drink,1003,1,[Coke],1.25
Carnitas Bowl,1007,1,"[Fresh Tomato (Mild), [Guacamole, Lettuce, Ric...",8.99
Carnitas Burrito,1003,1,"[Fresh Tomato (Mild), [Lettuce, Black Beans, G...",8.69
Carnitas Crispy Tacos,1774,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.99
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.99
Carnitas Salad Bowl,1035,1,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.39
Carnitas Soft Tacos,1011,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.99
Chicken Bowl,10,1,"[Fresh Tomato (Mild), [Guacamole, Rice]]",8.19
Chicken Burrito,1005,1,"[Fresh Tomato (Mild), [Black Beans, Rice, Sour...",8.19
Chicken Crispy Tacos,1010,1,"[Fresh Tomato Salsa (Mild), Fajita Veggies]",8.49
Chicken Salad,109,1,"[Fresh Tomato Salsa (Mild), Black Beans]",8.19
Chicken Salad Bowl,1015,1,"[Fresh Tomato Salsa, Fajita Vegetables]",8.75
Chicken Soft Tacos,1006,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
Chips,1005,1,NaN,1.99
Chips and Fresh Tomato Salsa,1,1,NaN,2.29
Chips and Guacamole,10,1,NaN,3.89
Chips and Mild Fresh Tomato Salsa,279,1,NaN,3.00
Chips and Roasted Chili Corn Salsa,102,1,NaN,2.95
Chips and Roasted Chili-Corn Salsa,1156,1,NaN,2.39
Chips and Tomatillo Green Chili Salsa,102,1,NaN,2.95
Chips and Tomatillo Red Chili Salsa,1020,1,NaN,2.95
Chips and Tomatillo-Green Chili Salsa,1,1,NaN,2.39
Chips and Tomatillo-Red Chili Salsa,1215,1,NaN,2.39
Crispy Tacos,217,1,[Adobo-Marinated and Grilled Chicken],7.40
Izze,1,1,[Blackberry],3.39
Nantucket Nectar,1,1,[Apple],3.39
Salad,575,1,"[Brown Rice, Adobo-Marinated and Grilled Chick...",7.40
Side of Chips,1002,1,NaN,1.69
Steak Bowl,1006,1,"[Fresh Tomato (Mild), [Guacamole, Lettuce, Pin...",8.69
Steak Burrito,100,1,[Brown Rice],8.69
Steak Crispy Tacos,1044,1,"[Fresh Tomato (Mild), [Lettuce, Cheese]]",8.69
Steak Salad,1406,1,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",8.69
Steak Salad Bowl,1032,1,"[Fresh Tomato Salsa, Lettuce]",9.39
Steak Soft Tacos,1054,1,"[Fresh Tomato Salsa (Mild), [Cheese, Sour Cream]]",8.99
Veggie Bowl,1006,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Blac...",8.49
Veggie Burrito,1033,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Faji...",8.49
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
Veggie Salad,1094,1,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
Veggie Salad Bowl,1066,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",8.75
Veggie Soft Tacos,1132,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

In [14]:
# sort_values() 함수를 적용하여 데이터를 정렬한다.
price_per_item = chipo_one_item.groupby('item_name').min()
price_per_item.sort_values(by = 'item_price',ascending = False)

,order_id,quantity,choice_description,item_price
item_name,,,,
Steak Salad Bowl,1032,1,"[Fresh Tomato Salsa, Lettuce]",9.39
Barbacoa Salad Bowl,1283,1,"[Fresh Tomato Salsa, Guacamole]",9.39
Carnitas Salad Bowl,1035,1,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.39
Carnitas Soft Tacos,1011,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.99
Carnitas Crispy Tacos,1774,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.99
Steak Soft Tacos,1054,1,"[Fresh Tomato Salsa (Mild), [Cheese, Sour Cream]]",8.99
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.99
Carnitas Bowl,1007,1,"[Fresh Tomato (Mild), [Guacamole, Lettuce, Ric...",8.99
Barbacoa Soft Tacos,1103,1,"[Fresh Tomato Salsa, [Black Beans, Cheese, Let...",8.99
Barbacoa Crispy Tacos,110,1,"[Fresh Tomato Salsa, Guacamole]",8.99
Veggie Salad Bowl,1066,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",8.75
Chicken Salad Bowl,1015,1,"[Fresh Tomato Salsa, Fajita Vegetables]",8.75
Steak Burrito,100,1,[Brown Rice],8.69
Steak Crispy Tacos,1044,1,"[Fresh Tomato (Mild), [Lettuce, Cheese]]",8.69
Steak Salad,1406,1,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",8.69
Carnitas Burrito,1003,1,"[Fresh Tomato (Mild), [Lettuce, Black Beans, G...",8.69
Steak Bowl,1006,1,"[Fresh Tomato (Mild), [Guacamole, Lettuce, Pin...",8.69
Barbacoa Burrito,1002,1,"[Fresh Tomato (Mild), [Black Beans, Rice, Sour...",8.69
Barbacoa Bowl,1000,1,"[Fresh Tomato (Mild), [Lettuce, Black Beans, R...",8.69
Chicken Soft Tacos,1006,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
Veggie Bowl,1006,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Blac...",8.49
Veggie Burrito,1033,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Faji...",8.49
Veggie Soft Tacos,1132,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
Chicken Crispy Tacos,1010,1,"[Fresh Tomato Salsa (Mild), Fajita Veggies]",8.49
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
Veggie Salad,1094,1,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
Chicken Salad,109,1,"[Fresh Tomato Salsa (Mild), Black Beans]",8.19
Chicken Burrito,1005,1,"[Fresh Tomato (Mild), [Black Beans, Rice, Sour...",8.19
Chicken Bowl,10,1,"[Fresh Tomato (Mild), [Guacamole, Rice]]",8.19
Crispy Tacos,217,1,[Adobo-Marinated and Grilled Chicken],7.40
Burrito,214,1,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",7.40
Bowl,279,1,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",7.40
Salad,575,1,"[Brown Rice, Adobo-Marinated and Grilled Chick...",7.40
6 Pack Soft Drink,1076,1,[Coke],6.49
Chips and Guacamole,10,1,NaN,3.89
Izze,1,1,[Blackberry],3.39
Nantucket Nectar,1,1,[Apple],3.39
Chips and Mild Fresh Tomato Salsa,279,1,NaN,3.00
Chips and Tomatillo Red Chili Salsa,1020,1,NaN,2.95
Chips and Tomatillo Green Chili Salsa,102,1,NaN,2.95
Chips and Roasted Chili Corn Salsa,102,1,NaN,2.95
Chips and Tomatillo-Red Chili Salsa,1215,1,NaN,2.39
Chips and Tomatillo-Green Chili Salsa,1,1,NaN,2.39
Chips and Roasted Chili-Corn Salsa,1156,1,NaN,2.39
Chips and Fresh Tomato Salsa,1,1,NaN,2.29
Chips,1005,1,NaN,1.99
Side of Chips,1002,1,NaN,1.69
Canned Soft Drink,1003,1,[Coke],1.25
Canned Soda,100,1,[Coca Cola],1.09
Bottled Water,1009,1,NaN,1.09

In [15]:
chipo.groupby('order_id').sum()

          quantity  item_price
order_id
1                4       11.56
10               2       13.20
100              2       10.08
1000             2       20.50
1001             2       10.08
...            ...         ...
995              3       24.95
996              4       43.00
997              2       22.50
998              2       10.88
999              5       29.25

[1834 rows x 2 columns]

In [16]:
# veggie salad bowl이 몇 번 주문 되었는지를 계산한다.
chipo[chipo['item_name'] == 'Veggie Salad Bowl']

,order_id,quantity,item_name,choice_description,item_price
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [17]:
print(chipo[chipo['item_name'] == 'Veggie Salad Bowl'].shape)

(18, 5)

In [18]:
Veggie_Salad = chipo[chipo['item_name'] == 'Veggie Salad Bowl']
Veggie_Salad.shape

(18, 5)

In [19]:
# 한 주문 내에서 중복 집계된 order_id를 제거한다.
Veggie_Salad = Veggie_Salad.drop_duplicates(['order_id'])
Veggie_Salad

,order_id,quantity,item_name,choice_description,item_price
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [20]:
Veggie_Salad.shape

(18, 5)

In [21]:
Veggie_Salad = chipo[chipo['item_name'] == 'Veggie Salad Bowl']
Veggie_Salad

,order_id,quantity,item_name,choice_description,item_price
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [22]:
# chicken bowl을 2개 이상 시킨 고객들의 veggie bowl 메뉴의 총 주문 수량을 구하자
chipo_chicken = chipo[chipo['item_name'] == 'Chicken Bowl']
chipo_chicken_result = chipo_chicken[chipo_chicken['quantity'] >= 2]
print(chipo_chicken_result.shape)
chipo_chicken_result

(33, 5)

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
154,70,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
282,124,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",17.50
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94
415,181,2,Chicken Bowl,[Tomatillo Red Chili Salsa],17.50
654,271,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
976,401,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
1017,418,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Black Beans]]",17.50
1106,457,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
1429,578,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Sour Cream, Guacam...",22.50
1514,616,3,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",26.25
1588,643,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
1832,741,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Sour Cream,...",21.96
2075,837,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",21.96
2106,848,2,Chicken Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",17.50
2339,932,2,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",16.98
2510,997,2,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",22.50
2525,1004,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...",21.96
2580,1023,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
2771,1100,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
2942,1170,2,Chicken Bowl,"[Tomatillo-Green Chili Salsa (Medium), [Black ...",21.96
3080,1227,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
3133,1249,2,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",16.98
3151,1257,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",21.96
3423,1374,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",17.50
3508,1410,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",21.96
3612,1447,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Cheese, Sou...",16.98
3618,1449,2,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
3663,1465,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
3843,1540,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Pinto...",21.96
3976,1593,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
4423,1764,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",22.50
4435,1767,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",17.50

In [23]:
chipo_chicken = chipo[chipo['item_name'] == 'Chicken Bowl']
chipo_chicken_result = chipo_chicken[chipo_chicken['quantity']>=2]
chipo_chicken_result = chipo_chicken_result.drop_duplicates(['order_id'])
print(chipo_chicken_result.shape)
chipo_chicken_result.head()

(33, 5)

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
154,70,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
282,124,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",17.50
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94
415,181,2,Chicken Bowl,[Tomatillo Red Chili Salsa],17.50

In [24]:
chipo_chicken = chipo[chipo['item_name'] == 'Chicken Bowl']
chipo_chicken.groupby('order_id')['quantity'].sum()

order_id
10      1
1000    1
1004    2
1006    1
1008    1
       ..
991     1
992     1
995     1
997     2
998     1
Name: quantity, Length: 615, dtype: int64

In [26]:
chipo_chicken_ordersum = chipo_chicken.groupby('order_id')['quantity'].sum()
results = chipo_chicken_ordersum[chipo_chicken_ordersum>=2]
print(len(results))

114